version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    volumes:
      - ./my_project:/var/www/html
    ports:
      - "8000:80"
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

